# Generated by Django 4.2 on 2024-08-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_contactus_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('subscribed', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, blank=True, max_length=0)),
                ('updated_at', models.DateTimeField(null=True,max_length=0)),
            ],
            options={
                'db_table': 'newsletter',
            },
        ),
    ]
