# Generated by Django 4.2 on 2024-08-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
