# Generated by Django 4.2 on 2024-08-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(null=True,max_length=1),
        ),
    ]
