# Generated by Django 4.2 on 2024-08-28 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_alter_testimonial_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'App'), (2, 'Product'), (3, 'Branding'), (4, 'Video')], default='1', max_length=100)),
                ('category', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=200)),
                ('project_date', models.DateField(blank=True)),
                ('project_url', models.CharField(blank=True, max_length=200)),
                ('short_description', models.TextField(blank=True, max_length=300)),
                ('long_description', models.TextField(blank=True)),
                ('image_1', models.CharField(blank=True, max_length=255, null=True)),
                ('image_2', models.CharField(blank=True, max_length=255, null=True)),
                ('image_3', models.CharField(blank=True, max_length=255, null=True)),
                ('image_4', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
    ]
