# Generated by Django 4.2 on 2024-08-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_alter_portfolio_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='type',
            field=models.CharField(choices=[(1, 'App'), (2, 'Product'), (3, 'Branding'), (4, 'Video')], max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
