# Generated by Django 4.2 on 2024-08-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_alter_portfolio_type_alter_portfolio_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='type',
            field=models.CharField(choices=[('1', 'App'), ('2', 'Product'), ('3', 'Branding'), ('4', 'Video')], default='1', max_length=100),
        ),
    ]
