# Generated by Django 4.2 on 2024-08-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_alter_portfolio_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='type',
            field=models.CharField(choices=[('App', 'App'), ('Product', 'Product'), ('Branding', 'Branding'), ('Video', 'Video')], default='App', max_length=100),
        ),
    ]
